os: osx
osx_image: xcode10.1
language: objective-c


install:
  - ./travis-build.sh

script:
  - cd ../
  - sudo tar -zcvf openssl.tar.gz openssl
  - - wget --method PUT --body-file=./openssl.tar.gz https://transfer.sh/openssl.tar.gz -O - -nv
