os: osx
osx_image: xcode8.3
language: objective-c


install:
  - ./travis-build.sh

script:
  - cd ../
  - sudo tar -zcvf openssl.tar.gz openssl
  - curl --upload-file ./openssl.tar.gz https://transfer.sh/
